export const currentUser = {
  id: "u1",
  name: "Kevin",
  avatar: "🎮",
  country: "🇦🇷",
  countryName: "Argentina",
  level: 3,
  levelName: "Amateur",
  xp: 340,
  xpNext: 500,
  points: 82,
  globalRank: 1234,
  streak: 5,
  precision: 67,
  predictions: 24,
  exactos: 6,
  groups: 3,
};

export const matches = [
  {
    id: "m1",
    teamA: { code: "ARG", name: "Argentina", flag: "🇦🇷" },
    teamB: { code: "BRA", name: "Brasil", flag: "🇧🇷" },
    date: "2026-06-08",
    time: "21:00",
    group: "Grupo A",
    status: "upcoming" as const,
    userPrediction: null,
  },
  {
    id: "m2",
    teamA: { code: "MEX", name: "México", flag: "🇲🇽" },
    teamB: { code: "ALE", name: "Alemania", flag: "🇩🇪" },
    date: "2026-06-08",
    time: "16:00",
    group: "Grupo B",
    status: "upcoming" as const,
    userPrediction: { scoreA: 1, scoreB: 2 },
  },
  {
    id: "m3",
    teamA: { code: "ESP", name: "España", flag: "🇪🇸" },
    teamB: { code: "JPN", name: "Japón", flag: "🇯🇵" },
    date: "2026-06-08",
    time: "13:00",
    group: "Grupo C",
    status: "upcoming" as const,
    userPrediction: { scoreA: 2, scoreB: 0 },
  },
  {
    id: "m4",
    teamA: { code: "FRA", name: "Francia", flag: "🇫🇷" },
    teamB: { code: "SEN", name: "Senegal", flag: "🇸🇳" },
    date: "2026-06-09",
    time: "19:00",
    group: "Grupo D",
    status: "upcoming" as const,
    userPrediction: null,
  },
  {
    id: "m5",
    teamA: { code: "ING", name: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    teamB: { code: "USA", name: "Estados Unidos", flag: "🇺🇸" },
    date: "2026-06-09",
    time: "16:00",
    group: "Grupo E",
    status: "upcoming" as const,
    userPrediction: null,
  },
  {
    id: "m6",
    teamA: { code: "POR", name: "Portugal", flag: "🇵🇹" },
    teamB: { code: "URU", name: "Uruguay", flag: "🇺🇾" },
    date: "2026-06-09",
    time: "13:00",
    group: "Grupo F",
    status: "upcoming" as const,
    userPrediction: { scoreA: 1, scoreB: 1 },
  },
  // Finished matches
  {
    id: "m7",
    teamA: { code: "ARG", name: "Argentina", flag: "🇦🇷" },
    teamB: { code: "MEX", name: "México", flag: "🇲🇽" },
    date: "2026-06-06",
    time: "21:00",
    group: "Grupo A",
    status: "finished" as const,
    scoreA: 2,
    scoreB: 1,
    userPrediction: { scoreA: 2, scoreB: 1 },
    pointsEarned: 3,
  },
  {
    id: "m8",
    teamA: { code: "BRA", name: "Brasil", flag: "🇧🇷" },
    teamB: { code: "SER", name: "Serbia", flag: "🇷🇸" },
    date: "2026-06-06",
    time: "16:00",
    group: "Grupo A",
    status: "finished" as const,
    scoreA: 2,
    scoreB: 0,
    userPrediction: { scoreA: 1, scoreB: 0 },
    pointsEarned: 1,
  },
];

export const groups = [
  {
    id: "g1",
    name: "Amigos del asado",
    emoji: "🏆",
    tournament: "Mundial 2026",
    members: 10,
    userPosition: 2,
    userPoints: 82,
    maxPoints: 96,
    hasPool: true,
    poolAmount: 50000,
    currency: "ARS",
    entryFee: 5000,
    poolDistribution: [50, 30, 20] as [number, number, number],
  },
  {
    id: "g2",
    name: "Oficina LATAM",
    emoji: "🏢",
    tournament: "Mundial 2026",
    members: 25,
    userPosition: 5,
    userPoints: 54,
    maxPoints: 96,
    hasPool: false,
    poolAmount: 0,
    currency: "ARS",
    entryFee: 0,
    poolDistribution: [50, 30, 20] as [number, number, number],
  },
  {
    id: "g3",
    name: "Compas de la facu",
    emoji: "🎓",
    tournament: "Mundial 2026",
    members: 8,
    userPosition: 1,
    userPoints: 72,
    maxPoints: 96,
    hasPool: true,
    poolAmount: 24000,
    currency: "ARS",
    entryFee: 3000,
    poolDistribution: [50, 30, 20] as [number, number, number],
  },
];

export const groupRanking = [
  { position: 1, userId: "u2", name: "Mati", avatar: "⚡", points: 96, streak: 6, isLeader: true, isUser: false },
  { position: 2, userId: "u1", name: "Kevin", avatar: "🎮", points: 82, streak: 5, isLeader: false, isUser: true },
  { position: 3, userId: "u3", name: "Nico", avatar: "🎯", points: 74, streak: 2, isLeader: false, isUser: false },
  { position: 4, userId: "u4", name: "Sofi", avatar: "💜", points: 71, streak: 0, isLeader: false, isUser: false },
  { position: 5, userId: "u5", name: "Facu", avatar: "🔥", points: 68, streak: 3, isLeader: false, isUser: false },
  { position: 6, userId: "u6", name: "Juli", avatar: "⭐", points: 65, streak: 1, isLeader: false, isUser: false },
  { position: 7, userId: "u7", name: "Tomi", avatar: "🎲", points: 61, streak: 0, isLeader: false, isUser: false },
  { position: 8, userId: "u8", name: "Lau", avatar: "🌟", points: 58, streak: 0, isLeader: false, isUser: false },
  { position: 9, userId: "u9", name: "Manu", avatar: "🏅", points: 52, streak: 0, isLeader: false, isUser: false },
  { position: 10, userId: "u10", name: "Gonza", avatar: "💀", points: 31, streak: 0, isLeader: false, isUser: false },
];

export const globalRanking = [
  { position: 1, name: "ProdeKing", avatar: "👑", country: "🇧🇷", points: 156, level: 15 },
  { position: 2, name: "ElCrack99", avatar: "⚡", country: "🇦🇷", points: 151, level: 14 },
  { position: 3, name: "FutbolGuru", avatar: "🧠", country: "🇲🇽", points: 148, level: 13 },
  { position: 4, name: "GolMaster", avatar: "⚽", country: "🇨🇴", points: 142, level: 12 },
  { position: 5, name: "LaLeyenda", avatar: "🏆", country: "🇦🇷", points: 139, level: 11 },
  { position: 6, name: "ProdePro", avatar: "🎯", country: "🇪🇸", points: 135, level: 11 },
  { position: 7, name: "Crack10", avatar: "🔥", country: "🇨🇱", points: 131, level: 10 },
  { position: 8, name: "GolDeOro", avatar: "✨", country: "🇺🇾", points: 128, level: 10 },
  { position: 9, name: "TacticoMX", avatar: "📊", country: "🇲🇽", points: 125, level: 9 },
  { position: 10, name: "QueGolazo", avatar: "🎮", country: "🇵🇪", points: 121, level: 9 },
];

export const badges = [
  { id: "b1", icon: "🎯", name: "Francotirador", description: "5 resultados exactos", earned: true, progress: 6, target: 5 },
  { id: "b2", icon: "🔥", name: "En llamas", description: "Racha de 5 aciertos", earned: true, progress: 5, target: 5 },
  { id: "b3", icon: "👑", name: "Lider", description: "Ser #1 en un grupo", earned: true, progress: 1, target: 1 },
  { id: "b4", icon: "🏆", name: "Campeon", description: "Ganar un torneo", earned: false, progress: 0, target: 1 },
  { id: "b5", icon: "📢", name: "Social", description: "Invitar 5 amigos", earned: true, progress: 7, target: 5 },
  { id: "b6", icon: "🌍", name: "Global", description: "Top 1000 mundial", earned: false, progress: 1234, target: 1000 },
  { id: "b7", icon: "💯", name: "Perfecto", description: "Acertar toda una fecha", earned: false, progress: 3, target: 4 },
  { id: "b8", icon: "💀", name: "Veterano", description: "Jugar 3+ torneos", earned: false, progress: 1, target: 3 },
  { id: "b9", icon: "🎮", name: "Gamer", description: "Usar 10 boosters", earned: false, progress: 2, target: 10 },
  { id: "b10", icon: "🏟️", name: "Fanatico", description: "Predecir 50 partidos", earned: false, progress: 24, target: 50 },
];

export const activityFeed = [
  { id: "a1", type: "exact", user: "Mati", text: "acerto el resultado exacto ARG 2-1 BRA", time: "hace 2 min", icon: "🏆" },
  { id: "a2", type: "rank_up", user: "Kevin", text: "subio al puesto #2", time: "hace 5 min", icon: "📈" },
  { id: "a3", type: "rank_down", user: "Gonza", text: "quedo ultimo otra vez", time: "hace 5 min", icon: "💀" },
  { id: "a4", type: "streak", user: "Mati", text: "tiene racha de 6 aciertos!", time: "hace 10 min", icon: "🔥" },
  { id: "a5", type: "join", user: "Lau", text: "se unio al grupo", time: "hace 1 hora", icon: "👋" },
  { id: "a6", type: "prediction", user: "Sofi", text: "hizo su prediccion para ESP vs JPN", time: "hace 2 horas", icon: "⚽" },
];

export interface PoolContribution {
  userId: string;
  name: string;
  avatar: string;
  paid: boolean;
  amount: number;
}

export const defaultPoolContributions: Record<string, PoolContribution[]> = {
  g1: [
    { userId: "u2", name: "Mati", avatar: "⚡", paid: true, amount: 5000 },
    { userId: "u1", name: "Kevin", avatar: "🎮", paid: false, amount: 5000 },
    { userId: "u3", name: "Nico", avatar: "🎯", paid: true, amount: 5000 },
    { userId: "u4", name: "Sofi", avatar: "💜", paid: true, amount: 5000 },
    { userId: "u5", name: "Facu", avatar: "🔥", paid: true, amount: 5000 },
    { userId: "u6", name: "Juli", avatar: "⭐", paid: true, amount: 5000 },
    { userId: "u7", name: "Tomi", avatar: "🎲", paid: false, amount: 5000 },
    { userId: "u8", name: "Lau", avatar: "🌟", paid: true, amount: 5000 },
    { userId: "u9", name: "Manu", avatar: "🏅", paid: true, amount: 5000 },
    { userId: "u10", name: "Gonza", avatar: "💀", paid: false, amount: 5000 },
  ],
  g3: [
    { userId: "u1", name: "Kevin", avatar: "🎮", paid: true, amount: 3000 },
    { userId: "u2", name: "Mati", avatar: "⚡", paid: true, amount: 3000 },
    { userId: "u3", name: "Nico", avatar: "🎯", paid: true, amount: 3000 },
    { userId: "u4", name: "Sofi", avatar: "💜", paid: false, amount: 3000 },
    { userId: "u5", name: "Facu", avatar: "🔥", paid: true, amount: 3000 },
    { userId: "u6", name: "Juli", avatar: "⭐", paid: true, amount: 3000 },
    { userId: "u7", name: "Tomi", avatar: "🎲", paid: true, amount: 3000 },
    { userId: "u8", name: "Lau", avatar: "🌟", paid: false, amount: 3000 },
  ],
};

export const levels = [
  { level: 1, name: "Novato", xp: 0 },
  { level: 2, name: "Hincha", xp: 100 },
  { level: 3, name: "Amateur", xp: 250 },
  { level: 4, name: "Jugador", xp: 500 },
  { level: 5, name: "Analista", xp: 1000 },
  { level: 7, name: "Tecnico", xp: 2500 },
  { level: 10, name: "Experto", xp: 5000 },
  { level: 15, name: "Elite", xp: 10000 },
  { level: 20, name: "Leyenda", xp: 25000 },
];
